### ISSUE TITLE
Buttons with a drop-down menu remove the scroll bar.

### ISSUE THREAD

**Issue by haruka98** [Crystal-Moon/ak-tcg#1]
## Description of the issue
Using buttons that open a drop-down menu removes the scroll bar on the page, shifting the entire page and removing scrolling functionality until closing the menu.

### Steps to reproduce
Click on any button with drop-down menu and try to scroll the page up or down.

### Expected result
The page should not remove the scroll bar when the menu opens.

### Actual result
The page removes the scroll bar, blocks all scrolling, and shifts all elements to the right until the menu is closed.

### Environment
OS: Windows 10 Pro 20H2
Browser: Google Chrome
Version: 92.0.4515.159

**Comment by Crystal-Moon** [comment]
Thanks for the contribution. This isn't a bug, it is normal behaviour of the select component of material-ui.
you can see the same result in the [demo documentation.](https://material-ui.com/components/selects/).

There are [some alternatives](https://github.com/mui-org/material-ui/issues/17353#issuecomment-565740350) to avoid scrolling lock, but they are really ugly.
